# Generated by Django 3.0.1 on 2019-12-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('mobile_no', models.CharField(max_length=10)),
                ('location', models.CharField(choices=[('mumbai', 'MUMBAI'), ('bangalore', 'BANGALORE'), ('pune', 'PUNE'), ('hyderabad', 'HYDERABAD'), ('kolkata', 'KOLKATA')], default='Mumbai', max_length=10)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Login')),
            ],
        ),
    ]
